function run(status, response) {

    // Tratamento das variáveis de entrada
    status = parseInt(status)
    response = JSON.parse(response)

    // Verifica se a response possui o atributo Contatos
    const hasContato = response.hasOwnProperty('Contatos')
    let contato;
    if (hasContato) {
        contato = response.Contatos;

        // Verifica se o atributo contato está vazio ou não
        if (Object.entries(contato).length == 0) {
            // Erro: Contato existe mas está vazio
            return JSON.stringify(
                {
                    type: "error",
                    status: status,
                    message: "Contato existe mas está vazio",
                    response: response
                }
            )
        } else {
            // Verifica qual o range do status da requisição
            if (status >= 200 && status <= 299) {
                return JSON.stringify(
                    {
                        type: "success",
                        status: status,
                        message: "Contato encontrado com sucesso",
                        response: response
                    }
                )
            } else {
                // Erro: Status diferente de 200-299
                return JSON.stringify(
                    {
                        type: "error",
                        status: status,
                        message: `Erro de status: ${status}`,
                        response: response
                    }
                )
            }
        }
    } else {
        // Erro: Response sem propriedade Contatos
        return JSON.stringify(
            {
                type: "error",
                status: status,
                message: "Response sem propriedade Contatos",
                response: response
            }
        )
    }
}







///////////////////////////
var status1 = "200";
var response1 = JSON.stringify({
    "Contatos": {}
})
var response2 = JSON.stringify({
    "Contatos": {
        "Contato": [
            {
                "itbc_lojaYomiName": null,
                "itbc_address1_cityName": "CHUI",
                "MasterContactIdYomiName": null,
                "PreferredEquipmentIdName": null,
                "new_lojaidName": null,
                "MasterContactIdName": null,
                "OriginatingLeadIdYomiName": null,
                "itbc_address1_countryName": "Brasil",
                "new_lojaidYomiName": null,
                "itbc_lojaName": null,
                "EntityImage_Timestamp": null,
                "ModifiedByName": "Administrador do CRM2015",
                "itbc_accountYomiName": null,
                "itbc_accountName": null,
                "CreatedOnBehalfByYomiName": null,
                "itbc_territoryName": null,
                "EntityImage": null,
                "ModifiedOnBehalfByYomiName": null,
                "CreatedByName": "Administrador do CRM2015",
                "ModifiedByYomiName": "Administrador do CRM2015",
                "TransactionCurrencyIdName": null,
                "PreferredSystemUserIdName": null,
                "new_ufidName": null,
                "new_regionalidName": null,
                "new_lista_marketingidName": null,
                "new_paisidName": null,
                "PreferredSystemUserIdYomiName": null,
                "new_cidadeidName": null,
                "PreferredServiceIdName": null,
                "DefaultPriceLevelIdName": null,
                "Address1_AddressTypeCode": null,
                "Address1_City": null,
                "Address1_Composite": "Sem campo cadastrado\r\n96255000",
                "Address1_Country": null,
                "Address1_County": null,
                "Address1_AddressId": "5419288D-E5F5-4C63-9809-9911D212E404",
                "Address1_Fax": null,
                "Address1_FreightTermsCode": null,
                "Address1_Latitude": null,
                "Address1_Line1": null,
                "Address1_Line2": "Sem campo cadastrado",
                "Address1_Line3": null,
                "Address1_Longitude": null,
                "Address1_Name": null,
                "Address1_PostalCode": "96255000",
                "Address1_PostOfficeBox": null,
                "Address1_PrimaryContactName": null,
                "Address1_ShippingMethodCode": null,
                "Address1_StateOrProvince": null,
                "Address1_Telephone1": null,
                "Address1_Telephone2": null,
                "Address1_Telephone3": null,
                "Address1_UPSZone": null,
                "Address1_UTCOffset": null,
                "Address2_AddressTypeCode": "1",
                "Address2_City": null,
                "Address2_Composite": null,
                "Address2_Country": null,
                "Address2_County": null,
                "Address2_AddressId": "13FADB23-C1A2-4B7D-8CA0-3D9F1A584826",
                "Address2_Fax": null,
                "Address2_FreightTermsCode": "1",
                "Address2_Latitude": null,
                "Address2_Line1": null,
                "Address2_Line2": null,
                "Address2_Line3": null,
                "Address2_Longitude": null,
                "Address2_Name": null,
                "Address2_PostalCode": null,
                "Address2_PostOfficeBox": null,
                "Address2_PrimaryContactName": null,
                "Address2_ShippingMethodCode": "1",
                "Address2_StateOrProvince": null,
                "Address2_Telephone1": null,
                "Address2_Telephone2": null,
                "Address2_Telephone3": null,
                "Address2_UPSZone": null,
                "Address2_UTCOffset": null,
                "Address3_AddressTypeCode": null,
                "Address3_City": null,
                "Address3_Composite": null,
                "Address3_Country": null,
                "Address3_County": null,
                "Address3_AddressId": "B579FD07-D9DE-44FF-A52D-4D56A7ED6F16",
                "Address3_Fax": null,
                "Address3_FreightTermsCode": null,
                "Address3_Latitude": null,
                "Address3_Line1": null,
                "Address3_Line2": null,
                "Address3_Line3": null,
                "Address3_Longitude": null,
                "Address3_Name": null,
                "Address3_PostalCode": null,
                "Address3_PostOfficeBox": null,
                "Address3_PrimaryContactName": null,
                "Address3_ShippingMethodCode": null,
                "Address3_StateOrProvince": null,
                "Address3_Telephone1": null,
                "Address3_Telephone2": null,
                "Address3_Telephone3": null,
                "Address3_UPSZone": null,
                "Address3_UTCOffset": null,
                "OwnerId": "9761F27F-6D00-E711-80BF-0050568D5DA2",
                "OwnerIdName": "Administrador do CRM2015",
                "OwnerIdYomiName": "Administrador do CRM2015",
                "OwnerIdDsc": "0",
                "OwnerIdType": "8",
                "OwningUser": "9761F27F-6D00-E711-80BF-0050568D5DA2",
                "OwningTeam": null,
                "AccountId": null,
                "AccountIdName": null,
                "AccountIdYomiName": null,
                "ParentContactId": null,
                "ParentContactIdName": null,
                "ParentContactIdYomiName": null,
                "ContactId": "47A8C648-F879-EC11-80E3-0050568DB649",
                "DefaultPriceLevelId": null,
                "CustomerSizeCode": "1",
                "CustomerTypeCode": "1",
                "PreferredContactMethodCode": "1",
                "LeadSourceCode": "1",
                "OriginatingLeadId": null,
                "OwningBusinessUnit": "430352B4-8FC5-E311-93FD-00155D013E56",
                "PaymentTermsCode": null,
                "ShippingMethodCode": "1",
                "ParticipatesInWorkflow": "false",
                "IsBackofficeCustomer": "false",
                "Salutation": null,
                "JobTitle": null,
                "FirstName": "jihad aymen mostafa",
                "Department": null,
                "NickName": null,
                "MiddleName": null,
                "LastName": null,
                "Suffix": null,
                "YomiFirstName": null,
                "FullName": "jihad aymen mostafa",
                "YomiMiddleName": null,
                "YomiLastName": null,
                "Anniversary": null,
                "BirthDate": null,
                "GovernmentId": null,
                "YomiFullName": "jihad aymen mostafa",
                "Description": "Contato criado chatbot",
                "EmployeeId": null,
                "GenderCode": null,
                "AnnualIncome": null,
                "HasChildrenCode": null,
                "EducationCode": "1",
                "WebSiteUrl": null,
                "FamilyStatusCode": null,
                "FtpSiteUrl": null,
                "EMailAddress1": "jihad.mostafa@intelbras.com.br",
                "SpousesName": null,
                "AssistantName": null,
                "EMailAddress2": null,
                "AssistantPhone": null,
                "EMailAddress3": null,
                "DoNotPhone": "false",
                "ManagerName": null,
                "ManagerPhone": null,
                "DoNotFax": "false",
                "DoNotEMail": "false",
                "DoNotPostalMail": "false",
                "DoNotBulkEMail": "false",
                "DoNotBulkPostalMail": "false",
                "AccountRoleCode": null,
                "TerritoryCode": "1",
                "IsPrivate": "false",
                "CreditLimit": null,
                "CreatedOn": "2022-01-20T11:53:03.000-02:00",
                "CreditOnHold": null,
                "CreatedBy": "9761F27F-6D00-E711-80BF-0050568D5DA2",
                "ModifiedOn": "2022-01-20T11:53:03.000-02:00",
                "ModifiedBy": "9761F27F-6D00-E711-80BF-0050568D5DA2",
                "NumberOfChildren": null,
                "ChildrensNames": null,
                "VersionNumber": "AAAAAeZGM+8=",
                "MobilePhone": "48998396088",
                "Pager": null,
                "Telephone1": null,
                "Telephone2": null,
                "Telephone3": null,
                "Fax": null,
                "Aging30": null,
                "StateCode": "0",
                "Aging60": null,
                "StatusCode": "1",
                "Aging90": null,
                "PreferredSystemUserId": null,
                "PreferredServiceId": null,
                "MasterId": null,
                "PreferredAppointmentDayCode": null,
                "PreferredAppointmentTimeCode": "1",
                "DoNotSendMM": "false",
                "ParentCustomerId": null,
                "Merged": "false",
                "ExternalUserIdentifier": null,
                "SubscriptionId": null,
                "PreferredEquipmentId": null,
                "LastUsedInCampaign": null,
                "ParentCustomerIdName": null,
                "ParentCustomerIdType": null,
                "TransactionCurrencyId": null,
                "OverriddenCreatedOn": null,
                "ExchangeRate": null,
                "ImportSequenceNumber": null,
                "TimeZoneRuleVersionNumber": "6",
                "UTCConversionTimeZoneCode": null,
                "AnnualIncome_Base": null,
                "CreditLimit_Base": null,
                "Aging60_Base": null,
                "Aging90_Base": null,
                "Aging30_Base": null,
                "ParentCustomerIdYomiName": null,
                "CreatedOnBehalfBy": null,
                "ModifiedOnBehalfBy": null,
                "IsAutoCreate": "false",
                "StageId": null,
                "ProcessId": null,
                "EntityImageId": null,
                "TraversedPath": null,
                "Business2": null,
                "Callback": null,
                "Company": null,
                "Home2": null,
                "itbc_AcaoCRM": "true",
                "itbc_address1_number": "0",
                "itbc_address1_street": "Sem campo cadastrado",
                "itbc_area": null,
                "itbc_Cargo": null,
                "itbc_CodigoDoEmitente": null,
                "itbc_CodigoDoRepresentante": null,
                "itbc_ContactNumber": null,
                "itbc_ContatoNFE": null,
                "itbc_CPFouCNPJ": "385.284.548-35",
                "itbc_DocIdentidade": null,
                "itbc_EmissorDocIdentidade": null,
                "itbc_Escolaridade": null,
                "itbc_IntegradoPor": "Integrador Barramento",
                "itbc_Nacionalidade": null,
                "itbc_Naturalidade": null,
                "itbc_PapelnoCanal": null,
                "itbc_ramal_fax": null,
                "itbc_Ramal_telefone1": null,
                "itbc_Ramal_telefone2": null,
                "itbc_ult_atualizacao_integracao": "2022-01-20T11:53:03.000-02:00",
                "itbc_UsuarioIntegracao": null,
                "itbc_account": null,
                "itbc_loja": null,
                "itbc_address1_stateorprovince": "25B03F0F-4CE9-E311-9420-00155D013D39",
                "itbc_address1_city": "CDA6D6D9-52E9-E311-9420-00155D013D39",
                "itbc_address1_country": "A06BE68E-4BE9-E311-9420-00155D013D39",
                "itbc_territory": null,
                "itbc_guidcrm40": null,
                "itbc_IntegraIntelbrasPontua": "false",
                "itbc_natureza": null,
                "New_acessoportal": "false",
                "New_administrador_fidelidade": "false",
                "New_Aniversario_Dia": null,
                "New_Aniversario_mes": null,
                "New_area": "99",
                "New_Cargo": "99",
                "New_Chave_Integracao": null,
                "New_consulta_relatorio_b2b": "false",
                "New_CPF": "38528454835",
                "New_cpf_sem_mascara": "38528454835",
                "New_Crm2013": null,
                "New_data_atualizacao_b2b": null,
                "New_Escolaridade": null,
                "New_Exporta_ERP": null,
                "New_ID": null,
                "New_Identificacao": null,
                "New_login": null,
                "New_Mensagem": null,
                "New_nao_permitir_sms": "false",
                "New_Numero_Endereco_Principal": null,
                "New_Observacao": null,
                "New_origem_contato": "993520000",
                "New_ParticipaFidelidade": "false",
                "New_PortalTreinamento": "false",
                "New_Ramal_Comercial2": null,
                "New_Ramal_fax": null,
                "New_ramal_telefone": null,
                "New_RG": null,
                "New_saldo_pontos_fidelidade": null,
                "New_Sequencia": null,
                "New_status_integracao": null,
                "New_total_pontos_resgatados": null,
                "new_lojaid": null,
                "new_lista_marketingid": null,
                "new_cidadeid": null,
                "new_paisid": null,
                "new_regionalid": null,
                "new_ufid": null,
                "itbc_areaatuacaotexto": null,
                "itbc_AreadeAtuacao": null,
                "itbc_DescricaodaAreadeAtuacao": null,
                "itbc_descricaodopapelnocanal": null,
                "itbc_integrabarramento": "true",
                "itbc_acesso": "false",
                "itbc_imei": null,
                "itbc_observacao": null,
                "itbc_acesso_app_isol": "false",
                "itbc_codigo_funcional": null,
                "itbc_treinamento": null,
                "itbc_CodigoFuncional": null,
                "itbc_acesso_solar": "false",
                "itbc_canais_de_venda": null,
                "itbc_exibir_site": "false"
            }
        ]
    }
})

console.log(run(status1, response2))